version: '3'
services:
  db:
    restart: always
    image: postgres
    ports:
      - "5431:5431"
    environment:
      - POSTGRES_DB=admin
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    ports:
      - 8081:8081
    depends_on:
      - db
      volumes:
        sample_db: {}